modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/wootrevived/industrialforegoingaddon/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/wootrevived/industrialforegoingaddon"
authors = "pharuxtan"
description = '''Woot Revived Addon that add compatibility with Industrial Foregoing'''

[[mixins]]
config = "ifwootaddon.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="woot_revived"
type = "required"
versionRange = "[${woot_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="industrialforegoing"
type = "required"
versionRange = "[${if_version},)"
ordering="NONE"
side="BOTH"
